In [1]:
%load_ext autoreload
%autoreload 2


In [2]:
import utils 
import numpy as np
import pandas as pd
import os

In [12]:
pd.set_option('display.max_colwidth', -1)
root_dir = os.path.abspath('.')
data_dir = os.path.join(root_dir, 'dataset')
train = pd.read_csv(os.path.join(data_dir,'train.csv'))
test = pd.read_csv(os.path.join(data_dir, 'test.csv'))


train_x, train_y = utils.featurize(train)
print(train_y[0:50])

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 1 1 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 1 0 1 1]
 [1 0 1 0 1 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [7]:
import sys
import numpy as np
import tkinter
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_validate
from sklearn.metrics import confusion_matrix
import pickle



In [23]:
tree = DecisionTreeClassifier(criterion="entropy",max_depth=3)
cv_results = cross_validate(tree,train_x,train_y,cv=5,return_estimator=True,return_train_score=False)

In [34]:
def column(matrix, i):
    return [row[i] for row in matrix]

In [35]:
print(cv_results['test_score'])
test=cv_results["estimator"][0]

print(test.predict(train_x[6].reshape(1, -1)))

[0.90202099 0.90524535 0.90646738 0.90477533 0.90606004]


array([[1., 0., 1., 0., 1., 0.]])

In [38]:
rf = RandomForestClassifier(n_estimators=100)
rf_cv_results=cross_validate(rf,train_x,train_y,cv=5,return_estimator=True,return_train_score=False)
print(rf_cv_results['test_score'])

[0.90449632 0.90596603 0.90806543 0.90734474 0.90819076]


In [ ]:
lr = []
lr.append(LogisticRegression(solver='lbfgs'))
lr.append(LogisticRegression(solver='lbfgs'))
lr.append(LogisticRegression(solver='lbfgs'))
lr.append(LogisticRegression(solver='lbfgs'))
lr.append(LogisticRegression(solver='lbfgs'))
lr.append(LogisticRegression(solver='lbfgs'))

i=0
while(i<6):
    
    lr_cv_results = cross_validate(lr[i],train_x,column(train_y,i),cv=5,return_estimator=True,return_train_score=False)
    print(lr_cv_results['test_score'])
    i+=1

In [ ]:
svc = []
svc.append(svm.SVC(gamma="auto"))
svc.append(svm.SVC(gamma="auto"))
svc.append(svm.SVC(gamma="auto"))
svc.append(svm.SVC(gamma="auto"))
svc.append(svm.SVC(gamma="auto"))
svc.append(svm.SVC(gamma="auto"))

j=0
while(j<6)
    svc_cv_results = cross_validate(svc[j],train_x,column(train_y,j),cv=3,return_estimator=True,return_train_score=False)
    print(svc_cv_results['test_score'])
    j+=1

In [ ]:
# when ready, set this to the best model you found, trained on the test data:
best_classifier = None

with open('classifier.pickle', 'wb') as f: # 'wb' stands for 'write bytes'
    pickle.dump(best_classifier, f)